name: flanders
channels:
  - defaults
dependencies:
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - async-timeout=4.0.2
  - asynctest=0.13.0
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - c-ares=1.18.1
  - ca-certificates=2022.10.11
  - cachetools=4.2.2
  - certifi=2022.9.24
  - cffi=1.15.1
  - click=8.0.4
  - cryptography=38.0.1
  - dataclasses=0.8
  - fftw=3.3.9
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.4
  - idna=3.4
  - intel-openmp=2021.4.0
  - libcxx=14.0.6
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libprotobuf=3.20.1
  - llvm-openmp=14.0.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.2
  - ncurses=6.3
  - numpy-base=1.21.5
  - oauthlib=3.2.1
  - openssl=1.1.1s
  - pip=22.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.7.13
  - readline=8.2
  - requests=2.28.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - setuptools=65.5.0
  - six=1.16.0
  - sqlite=3.39.3
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.6.0
  - tk=8.6.12
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - urllib3=1.26.12
  - wheel=0.37.1
  - xz=5.2.6
  - yarl=1.8.1
  - zlib=1.2.13
  - pip:
    - absl-py==1.2.0
    - astor==0.8.1
    - attrs==22.1.0
    - bleach==1.5.0
    - charset-normalizer==2.1.1
    - cycler==0.11.0
    - distlib==0.3.6
    - filelock==3.8.0
    - flwr==1.0.0
    - fonttools==4.37.4
    - frozenlist==1.3.1
    - gast==0.2.2
    - google-pasta==0.2.0
    - grpcio==1.43.0
    - h5py==2.10.0
    - html5lib==0.9999999
    - importlib-metadata==4.13.0
    - importlib-resources==5.9.0
    - iterators==0.0.2
    - joblib==1.2.0
    - jsonschema==4.16.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.4
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.5.3
    - msgpack==1.0.4
    - natsort==8.2.0
    - numpy==1.18.5
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandas==1.3.5
    - pillow==9.2.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==2.5.2
    - protobuf==3.20.3
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytz==2022.4
    - pyyaml==6.0
    - ray==1.13.0
    - seaborn==0.12.0
    - sklearn==0.0
    - tensorboard==1.15.0
    - tensorflow==1.15.5
    - tensorflow-estimator==1.15.1
    - tensorflow-tensorboard==1.5.1
    - termcolor==2.0.1
    - threadpoolctl==3.1.0
    - torch==1.12.1
    - torchvision==0.13.1
    - tqdm==4.64.1
    - virtualenv==20.16.5
    - werkzeug==2.2.2
    - wrapt==1.14.1
    - zipp==3.8.1
